In [1]:
import numpy as np

from scipy.linalg import expm as la_expm
from scipy.sparse.linalg import expm as sp_expm
import scipy.sparse as sp
from scipy.integrate import solve_ivp

import matplotlib.pyplot as plt

from deepburn.CRAM import CRA, CRAC, CRA_ODEsolver
from deepburn.CRAM import cras_literature as cl

np.set_printoptions(precision=16)

In [2]:
#Polonium problem

A = np.array([[-1.83163e-12,0,0],[+1.83163e-12,-1.60035e-6,0],[0,+1.60035e-6,-5.79764e-8]])
def Ydot(t,Y):
    A = np.array([[-1.83163e-12,0,0],[+1.83163e-12,-1.60035e-6,0],[0,+1.60035e-6,-5.79764e-8]])
    return A.dot(Y)
    
Y0 = np.array([6.95896e-4,0,0])


## Solving with Radau ##

In [3]:
oneY = 365.25*24*3600
Y_Radau = solve_ivp(Ydot,(0, oneY), Y0, method="Radau", rtol=1e-12, atol = 1e-30, t_eval=[oneY])
print(Y_Radau.y)

[[6.9585577708845012e-04]
 [7.9642064281967071e-10]
 [1.8323781965287107e-08]]


## Solving with expm from SciPy dense ##

In [4]:
Y_expmdense = np.dot(la_expm(A*oneY),Y0)
print(Y_expmdense)

[6.9585577708844806e-04 7.9642064281966834e-10 1.8323781965286988e-08]


## Solving with expm from SciPy sparse ##

In [5]:
Asp = sp.csc_matrix(A)
Y_expsp = sp.linalg.expm(Asp*oneY) *Y0
print(Y_expsp)

[6.9585577708844806e-04 7.9642064281966823e-10 1.8323781965286994e-08]


## Solving with CRA from DeepBurn ##

In [6]:
cras = CRA_ODEsolver()
Y_cras = cras._solveCRA(A*oneY, Y0)
print(Y_cras)

[6.958557770884381e-04 7.964206428196540e-10 1.832378196528666e-08]


In [7]:
cras = CRA_ODEsolver()
Y_cras = cras._solveCRA(Asp*oneY, Y0)
print(Y_cras)

[6.958557770884329e-04 7.964206428196540e-10 1.832378196528666e-08]
